name: Build e Empacotamento Nativo do Agente Java

on:
  push:
    tags:
      - '*.*.*' # Exemplo: 1.0.0 

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    env:
      MAVEN_PROJECT_DIR: looca-api
      EXECUTABLE_BASE_NAME: OberonAgenteJava
      MAIN_CLASS: com.oberon.monitoramento.Main
      JAR_NAME: looca-api 
      
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java Amazon Corretto 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Build do Projeto com Maven
        run: mvn clean package -f ${{ env.MAVEN_PROJECT_DIR }}/pom.xml
      - name: Criar JRE customizado (jlink)
        run: jlink --output jre_min --add-modules java.base,java.sql,java.desktop,java.management,java.logging,java.naming,jdk.unsupported

      - name: Localizar JAR e Configurar Caminhos
        id: paths
        shell: bash
        run: |
          JAR_PATH=$(find ${{ env.MAVEN_PROJECT_DIR }}/target -name "${{ env.JAR_NAME }}*.jar" -print -quit)
          if [ -z "$JAR_PATH" ]; then
              echo "Erro: JAR com nome base '${{ env.JAR_NAME }}' não encontrado em target/. Por favor, verifique o pom.xml."
              exit 1 
          fi
          
          mkdir -p dist/package
          cp "$JAR_PATH" dist/package/app.jar
          
          if [[ "$RUNNER_OS" == "Windows" ]]; then
              INSTALLER_NAME="${{ env.EXECUTABLE_BASE_NAME }}.exe"
          else
              INSTALLER_NAME="${{ env.EXECUTABLE_BASE_NAME }}"
          fi
          
          echo "INSTALLER_NAME=$INSTALLER_NAME" >> $GITHUB_ENV
          echo "DIST_PATH=dist" >> $GITHUB_OUTPUT

      - name: Criar Pacote Nativo (EXE para Windows / Executável para Linux)
        shell: bash 
        run: |
          APP_VERSION_STRIPPED="${{ github.ref_name }}"
          
          PACKAGE_TYPE="app-image" 
          
          jpackage \
            --name ${{ env.EXECUTABLE_BASE_NAME }} \
            --app-version $APP_VERSION_STRIPPED \
            --input dist/package \
            --dest dist \
            --main-jar app.jar \
            --main-class ${{ env.MAIN_CLASS }} \
            --runtime-image jre_min \
            --type $PACKAGE_TYPE \
            --verbose

      - name: Preparar Variáveis de Nome de ZIP
        id: prepare_vars
        shell: bash
        run: |
          VERSION="${{ github.ref_name }}"
          BASE_NAME="${{ env.EXECUTABLE_BASE_NAME }}"
          
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            OS_SUFFIX="Windows"
          else
            OS_SUFFIX="Linux"
          fi
          
          ZIP_NAME="${BASE_NAME}-${VERSION}-${OS_SUFFIX}.zip"
          
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          echo "zip_path_output=$ZIP_NAME" >> $GITHUB_OUTPUT
          
      - name: Criar ZIP (Windows)
        if: runner.os == 'Windows'
        shell: bash 
        run: |
          BASE_NAME="${{ env.EXECUTABLE_BASE_NAME }}"
          "/c/Program Files/7-Zip/7z.exe" a -tzip "${{ env.ZIP_NAME }}" "dist/$BASE_NAME"

      - name: Criar ZIP (Linux)
        if: runner.os == 'Linux'
        shell: bash 
        run: |
          BASE_NAME="${{ env.EXECUTABLE_BASE_NAME }}"
          DIST_PATH="dist"
          
          zip -r "${{ env.ZIP_NAME }}" "$DIST_PATH/$BASE_NAME"

      - name: Upload do ZIP como artefato
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_NAME }}

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Criar Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          
      - name: Baixar todos os artefatos
        uses: actions/download-artifact@v4
        with:
          path: ./assets
          pattern: '*'
          merge-multiple: true 
          
      - name: Enviar assets à Release
        run: |
          set -e
          
          RELEASE_UPLOAD_URL_CLEANED=$(echo "${{ steps.create_release.outputs.upload_url }}" | sed 's/{?name,label}//')
          
          if [ $(find ./assets -name "*.zip" | wc -l) -eq 0 ]; then
            echo "Aviso: Nenhum arquivo .zip encontrado para upload."
            exit 0
          fi
          
          find ./assets -name "*.zip" -print0 | while IFS= read -r -d $'\0' FILE
          do
            ABSOLUTE_PATH="$PWD/$FILE"
            ASSET_NAME=$(basename "$FILE")
            
            FINAL_URL="${RELEASE_UPLOAD_URL_CLEANED}?name=$ASSET_NAME"
            
            curl -sSL \
              -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/octet-stream" \
              --data-binary "@$ABSOLUTE_PATH" \
              "$FINAL_URL"
          done
